on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1                            # Azure login required to add a temporary firewall rule
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/sql-action@v1.3
      with:        
        connection-string: ${{ secrets.MMMPIZZA_AZURE_SQL_CONNECTION_STRING }}
        project-file: './Source/SuperHeroes/SuperHeroes.sqlproj'
        build-arguments: '-c Release'                 # Optional arguments passed to dotnet build
        arguments: '/p:DropObjectsNotInSource=false'   # Optional parameters for SqlPackage Publish